### ISSUE TITLE
Update the SafeMySQL class

### ISSUE THREAD

**Issue by dalai-lamia** [ionutvmi/master-login-system#11]
Hello,
This is a great system but it uses an early version of the SafeMySQL class, which has been updated several times since June 2013. Do you have the time to update the mysql.class.php file included in your system?
Thanks!

**Comment by dalai-lamia** [comment]
I have tried to identify your edits to the class and transfer them to the updated safemysql.class.php but I must be missing something because when I include the new file on line #20 of inc/init.php I get an error (Notice: Trying to get property of non-object in ...\lib\presets.class.php on line <i>48</i>) 

The edits I have identified and transferred to the new version of safemysql.class.php are as follows:

1. public $asObj; --- line 74
2. 'asObj'     => true, --- line 87
3. $this->asObj = $opt['asObj']; --- line 99
4. The whole public function ret($value) --- lines 137-146
5. The changes you've made to private function prepareQuery($args) --- lines 495-566.

I couldn't find anything else but I amobviously missing something as I do not get the above error when I use your version of the SafeMySQL class.

**Comment by ionutvmi** [comment]
Hi, 
Do you have any problems with the current version of safemysql ?
This is not a project I currently work on but I am happy to accept a pull request with those changes.

**Comment by dalai-lamia** [comment]
No, not really. Just thought it a good idea to update. I mean, if the developer of the SafeMySQL class has found it necessary to improve his code, then he is aware of potential issues. And since it has taken me - a non-expert - about 30 minutes to update, I suppose it will take you much less. But the decision is yours. Cheers!

**Comment by ionutvmi** [comment]
I had a look over the changes.
Apart from the option to pass an existing mysqli instance there were no other major changes (or bug fixes).
So I think we are good with the current version.
