### ISSUE TITLE
Cateva intrebari!

### ISSUE THREAD

**Issue by efido** [ionutvmi/master-login-system#12]
Salut Ionut, spune-mi si mie te rog care este rolul in momentul cand dai ban cuiva cu scriptul asta, pentru ca am vazut ca indiferent daca userul este banat nu afecteaza cu nimic, userul se poate loga, poate sa navigheze contul lui cu usurinta, nu poti face si tu sa ii blocheze contul si accesul la meniuri, content? Si in alta ordine de idei, crezi ca este greu sa faci un friend sistem, bazat pe conturile din script? Si ultima intrebare, se poate plasa content diferit pe fiecare pagina de user?

**Comment by ionutvmi** [comment]
Salut @efido,
Momentan atunci cand un utilizator este banat acesta primeste un mesaj de notificare in header.
In functie de aplicatia pe care doresti sa o construiesti poti limita accesul la anumite pagini sau chiar la intreaga aplicatie pentru un utilizator autentificat dar aceasta logica trebuie adauga de tine.

Poti implementa orice tip de aplicatie doresti pe baza acestui script.

**Comment by efido** [comment]
Mihai, imi poti face si mie te rog un proces mic gen cand ii dai ban la un user sa ii dezactiveze pagina si sa ii scrie user banned ceva de genu ? Sau sa imi oferi niste pasi din scriptul tau cum sa ajung la acest proces? as aprecia mult , ms frumos 

    În Luni, 18 Ianuarie 2016 20:12:38, Mihai Ionut Vilcu <notifications@github.com> a scris:
 

 Salut @efido,
Momentan atunci cand un utilizator este banat acesta primeste un mesaj de notificare in header.
In functie de aplicatia pe care doresti sa o construiesti poti limita accesul la anumite pagini sau chiar la intreaga aplicatie pentru un utilizator autentificat dar aceasta logica trebuie adauga de tine.Poti implementa orice tip de aplicatie doresti pe baza acestui script.—

**Comment by ionutvmi** [comment]
@efido ar trebui sa fie ceva de genul
```
if ($user->getBan()) {
     echo "You are banned !";
     die();
}
```

**Comment by efido** [comment]
Am introdus ce mi-ai relatat tu mai sus, dar imi da crash: 
Notice: Undefined variable: user 
Fatal error: Call to a member function getBan() on null 
--
Am adaugat procesul tau in ; user.class.php , e ok  ? Sau am gresit eu? Si limitarea accesului la header as vrea cat si la profil sa il dezactiveze si sa ii apara ce mi-ai scris tu in echo. Ms frumos pt sprijin, chiar m-ar ajuta mult. Stima!
--

**Comment by ionutvmi** [comment]
Codul ar trebui sa fie pus dupa ce se include init.php. Poti arunca o privire la index.php sa vezi cum e structurata o pagina.
Un exemplu de folosire a codului poti gasi in header.php.

**Comment by efido** [comment]
ok ms, am reusit

**Comment by StirbuDaniel** [comment]
Salut Ionut, am modificat scriptul tau si mi-au iesit toate cum am vrut dar, am o mare problema, nu gasesc de unde sa modific nav barul.

**Comment by efido** [comment]
header.php si lib/presets.class.php :)
