### ISSUE TITLE
thanks for ur work bro 

### ISSUE THREAD

**Issue by khanems** [ionutvmi/master-login-system#13]
![screenshot_1](https://cloud.githubusercontent.com/assets/11493447/12403722/a73afcf6-be57-11e5-887c-28096c9642f8.png)

here is the new look if u want i can share it

**Comment by khanems** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/11493447/12403759/0811ab2e-be58-11e5-92dd-46556426b697.png)

**Comment by efido** [comment]
Can u share it ? mail: haotix@yahoo.com
