### ISSUE TITLE
Additional security measure

### ISSUE THREAD

**Issue by pawnu** [ionutvmi/master-login-system#15]
It would be nice to have the passwords salted after hashing with SHA1. Most developers would argue against using SHA1 for hashing password since computers are more capable of reversing the hashes of SHA1 nowadays and we all know most users tend to use simple passwords which makes it easier to carry out known plaintext attack and rainbow table attacks if your server was compromised.

If attacker can brute force one hash and multiple users were using the same password, they would also be vulnerable because in your code 2 password hashes stored in the databases would be the same if 2 users were to choose the same password. 

One simple solution is to hash password using `password_hash()` function which is a feature of PHP 5.5 which salts and stretches the plaintext and also chooses the best algorithm (future proofing) during execution. To verify the hash simply use `password_verify()` function, this will check the hash algorithm information, salt and hashed password.

Also, your login.php page doesn't seem to have protection against multiple login attempt which could facilitate bruteforce login attack. To prevent multiple login attemts, each user could have an additional field in database which could be used for locking the user for certain period (maybe 10-30 min) after certain number of failed login attempts. You could also implement a captcha request after a certain number of unsuccessful login attempts.

**Comment by ionutvmi** [comment]
Closing this issue as a PR was created to address this. We will continue the discussion there. #17
