### ISSUE TITLE
creation of uersgroup not part of member

### ISSUE THREAD

**Issue by nlmaca** [ionutvmi/master-login-system#19]
found a small bug. when creating a new group and you add it to type: member and save it, the group getst the type guest and not member. 
when returning to the group management you will see the new group, but it has the type guest. 
when editing the group and set it to the type member then it will be correct. 

so on creation of the group the type isn't set correctly

**Comment by nlmaca** [comment]
Your fix didnt work. i still have the same problem after deploying your latest version.

**Comment by ionutvmi** [comment]
Seems to work fine for me locally.
Please make sure that you included the code correctly and it should work.

**Comment by nlmaca** [comment]
fixed now. i only copied the file changes you made. i did a complete reinstall. that fixed it. thx.
