### ISSUE TITLE
Access without login

### ISSUE THREAD

**Issue by PrestaShark** [ionutvmi/master-login-system#26]
Hi,
I have noticed when user is logout from the system and know the direct link can view the content... How to fix it?

PS> many thanks for this contribution!

**Comment by PrestaShark** [comment]
This code make the right job

```
if(!$user->islg()) {
header("Location: $set->url");
exit;
}
```

So add this to all pages that You want to hide to non registred/logged user

**Comment by ionutvmi** [comment]
I will close this issue since you found the solution.
