### ISSUE TITLE
there is an issue installation

### ISSUE THREAD

**Issue by amitsavla** [ionutvmi/master-login-system#31]
![image](https://cloud.githubusercontent.com/assets/20124013/23599354/89c11d78-0266-11e7-892f-403c263ab203.png)

how to solve it?

**Comment by MchlBowyer** [comment]
This means the site could not connect to the database using the credentials you supplied. Make sure the details are correct and try again (also make sure the database mls actually exists, or change it to the correct name of an empty database).
