### ISSUE TITLE
Persistant Authenticated XSS via display name

### ISSUE THREAD

**Issue by rootabeta** [ionutvmi/master-login-system#43]
An authenticated user can insert arbitrary HTML elements, including <script>, by placing said elements in the display name field for their profile in the update profile interface. This code is then interpreted and (in the case of script) run in the browser of anyone who views the profile of the malicious user (for example, in "My Profile"). 
In the example below, the payload is simply `<script>alert("XSS");</script>` in the display name field, without obfuscation. 
![screenshot_00000](https://user-images.githubusercontent.com/29870550/83986730-d6b2d500-a90b-11ea-9d4c-85fa126b900a.png)

**Comment by ionutvmi** [comment]
@VinylCarbon are you still maintaining this project ?

**Comment by rootabeta** [comment]
Update: after further investigation it is likely that this is caused by a thought-to-be-minor modification made to my testing platform, and likely does not correspond to this particular version. As a result I will be closing this issue.
