### ISSUE TITLE
Compare table field

### ISSUE THREAD

**Issue by khanems** [ionutvmi/master-login-system#8]
thanks for the code bro
i am having issue with moding the code in header.php
i have member field with expire date 
now i want to compare expire date with this date("d/m/y")
 ```php
// we will add the expired user to ban
    $_enban = $db->getAll("SELECT `userid` FROM `".MLS_PREFIX."users` WHERE `expiredate` = ".date("d/m/y"));
    if($_enban) 
        foreach ($_enban as $_usr) {
            $db->query("UPDATE `".MLS_PREFIX."users` SET `banned` = '1' WHERE `userid` = ?i", $_usr->userid); 
            $db->query("INSERT INTO `".MLS_PREFIX."banned` SET `userid` = ?i, `username` = 'admin', `by` = '1', `until` = '1434778187', `reason` = 'Payment is due' ", $_usr->userid);            
        }
		}
```
thanks please help me out

**Comment by ionutvmi** [comment]
Assuming that `expiredate` is a unix timestamp something like this should work:
```
$_enban = $db->getAll("SELECT `userid` FROM `".MLS_PREFIX."users` WHERE `expiredate` < ". time());
```
You should check what type you selected for the column `expieredate` and do the proper comparison.
Google should help on that.

**Comment by khanems** [comment]
i am not using timestamp for that for expiredate i just use 02/01/15

**Comment by ionutvmi** [comment]
check in phpmyadmin what is the type of the `expiredate` columns.
If you want to store a date I recommend using ether a timestamp or a date and then you should be able to compare them.
If you stored it as a string the comparison won't work.

Also closing this issue as it is not related to the script present in this repo.
