### ISSUE TITLE
Mlc database

### ISSUE THREAD

**Issue by gujjardada** [ionutvmi/master-login-system#9]
WHen i install the install.php file in my browser then it show me 
Error: 1049 Unknown database 'mls'
can u help me please

**Comment by ionutvmi** [comment]
Please make sure you create a database before running the install script.
Please have a look over the install form and make sure you have all the information available before you click install.

**Comment by gujjardada** [comment]
In your video you created mlc_user and many other can You please send me the pics of your database please my email id:
hearthackerjan@outlook.com

**Comment by ionutvmi** [comment]
All you need is an empty database in order to install this script.
The tables and the initial data are created by the install.php script.

**Comment by Anjali-Pai** [comment]
Error: 2002 No such file or directory . How to solve this error , please help .

**Comment by ionutvmi** [comment]
Where do you get that error ?

**Comment by mlungsta** [comment]
Hello, thank you for the script. I am a beginner but i managed to create the tables and connect to the database however when i click "install" i get an error that says: " There was a problem while executing INSERT INTO 'mls_privacy' ('userid', 'email') VALUES (1, 0); " I have deleted and created the privacy table again following steps in the install.php but still i am not coming right. What could be the problem? I am looking forward to your response. Thanks
